export const lenguajes = [
        'Vercel/Netlify',
        'HTML',
        'CSS/Sass/Less',
        'Tailwind',
        'Bootstrap',
        'Material UI',
        'Vuetify',
        'Firebase',
        'Git',
        'Github',
        'MongoDb',
        'Sql/NoSql',
        'ReactJS',
        'NextJS',
        'VueJS',
        'Django',
        'Python',
        'Javascript',
        'Typescript',
        'NodeJS/Express',
        'PHP',
]